### ISSUE TITLE
32bit Linux Amalgamation broken

### ISSUE THREAD

**Issue by webmaster128** [randombit/botan#259]
When Botan is build for Linux 32 bit, GCC does not enable SSE2. But this is used in `botan_all_internal.h` from [simd_sse2.h](https://github.com/randombit/botan/blob/master/src/lib/utils/simd/simd_sse2/simd_sse2.h).

```
$ ./configure.py --build-mode=debug --disable-shared --via-amalgamation && make
   INFO: Platform: OS="Linux" machine="i686" proc="i686"
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Guessing target processor is a x86_32/i686 (use --cpu to set)
   INFO: Target is gcc-linux-x86_32-i686
   INFO: Skipping, by request only - cvc
   INFO: Skipping, dependency failure - sessions_sqlite3
   INFO: Skipping, incompatible CPU - mp_x86_64 simd_altivec
   INFO: Skipping, incompatible OS - beos_stats cryptoapi_rng win32_stats
   INFO: Skipping, incompatible compiler - mp_x86_32_msvc
   INFO: Skipping, loaded only if needed by dependency - dyn_load mp_generic simd_scalar
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlite3 zlib
   INFO: Using MP module mp_x86_32
   INFO: Using SIMD module simd_sse2
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 alloc aont asn1 auto_rng base base64 bcrypt benchmark bigint block blowfish camellia cascade cast cbc cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compression crc24 crc32 credentials cryptobox ctr curve25519 datastor des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa egd elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa1_bsi emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash hash_id hex hkdf hmac hmac_drbg hmac_rng hres_timer http_util idea idea_sse2 if_algo kasumi kdf kdf1 kdf2 keccak keypair lion locking_allocator mac mars mce mceies md2 md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp mp_x86_32 noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc2 rc4 rc5 rc6 rdrand rfc3394 rfc6979 rmd128 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha2_32 sha2_64 simd simd_sse2 siphash siv skein srp6 stream system_rng tea threefish threefish_avx2 tiger tls tss twofish unix_procs utils whirlpool x509 x919_mac x931_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Writing amalgamation source to botan_all_aesni.cpp
   INFO: Writing amalgamation source to botan_all_ssse3.cpp
   INFO: Writing amalgamation source to botan_all_sse2.cpp
   INFO: Writing amalgamation source to botan_all_rdrand.cpp
   INFO: Writing amalgamation source to botan_all_avx2.cpp
   INFO: Botan 1.11.20 (unreleased undated) build setup is complete
g++ -pthread -fstack-protector  -std=c++11 -D_REENTRANT -c -g -O0 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Ibuild/include botan_all.cpp -o build/obj/lib/botan_all.o
In file included from botan_all_internal.h:2955:0,
                 from botan_all.cpp:9:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
In file included from botan_all.cpp:9:0:
botan_all_internal.h:3101:25: error: expected ‘)’ before ‘in’
       SIMD_SSE2(__m128i in) { reg = in; }
                         ^
botan_all_internal.h:3103:7: error: ‘__m128i’ does not name a type
       __m128i reg;
       ^
```

**Comment by randombit** [comment]
Fixed in 97b6e192e752fe8a0fd95116a84d7b29d8ed71f5

**Comment by webmaster128** [comment]
Not fixed, sorry.

```
$ ./configure.py --build-mode=debug --disable-shared --via-amalgamation && make
   INFO: Platform: OS="Linux" machine="i686" proc="i686"
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Guessing target processor is a x86_32/i686 (use --cpu to set)
   INFO: Target is gcc-linux-x86_32-i686
   INFO: Skipping, by request only - cvc
   INFO: Skipping, dependency failure - sessions_sqlite3
   INFO: Skipping, incompatible CPU - mp_x86_64 simd_altivec
   INFO: Skipping, incompatible OS - beos_stats cryptoapi_rng win32_stats
   INFO: Skipping, incompatible compiler - mp_x86_32_msvc
   INFO: Skipping, loaded only if needed by dependency - dyn_load mp_generic simd_scalar
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlite3 zlib
   INFO: Using MP module mp_x86_32
   INFO: Using SIMD module simd_sse2
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 alloc aont asn1 auto_rng base base64 bcrypt benchmark bigint block blowfish camellia cascade cast cbc cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compression crc24 crc32 credentials cryptobox ctr curve25519 datastor des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa egd elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa1_bsi emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash hash_id hex hkdf hmac hmac_drbg hmac_rng hres_timer http_util idea idea_sse2 if_algo kasumi kdf kdf1 kdf2 keccak keypair lion locking_allocator mac mars mce mceies md2 md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp mp_x86_32 noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc2 rc4 rc5 rc6 rdrand rfc3394 rfc6979 rmd128 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha2_32 sha2_64 simd simd_sse2 siphash siv skein srp6 stream system_rng tea threefish threefish_avx2 tiger tls tss twofish unix_procs utils whirlpool x509 x919_mac x931_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Writing amalgamation source to botan_all_aesni.cpp
   INFO: Writing amalgamation source to botan_all_ssse3.cpp
   INFO: Writing amalgamation source to botan_all_sse2.cpp
   INFO: Writing amalgamation source to botan_all_rdrand.cpp
   INFO: Writing amalgamation source to botan_all_avx2.cpp
   INFO: Botan 1.11.20 (unreleased undated) build setup is complete
g++ -pthread -fstack-protector  -std=c++11 -D_REENTRANT -c -g -O0 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Ibuild/include botan_all.cpp -o build/obj/lib/botan_all.o
In file included from botan_all_internal.h:2955:0,
                 from botan_all.cpp:9:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
In file included from botan_all.cpp:9:0:
botan_all_internal.h:3101:25: error: expected ‘)’ before ‘in’
       SIMD_SSE2(__m128i in) { reg = in; }
                         ^
botan_all_internal.h:3103:7: error: ‘__m128i’ does not name a type
       __m128i reg;
       ^
```

From those lines I read, that `emmintrin.h` must not be included in any Non-SSE2 object but in botan_all_internal.h we have

```
   2951 
   2952 #if defined(BOTAN_HAS_SIMD_SSE2)
   2953 #if defined(BOTAN_TARGET_SUPPORTS_SSE2)
   2954 
   2955 #include <emmintrin.h>
   2956 
   2957 namespace Botan {
   2958 
   2959 class SIMD_SSE2
   2960    {
   2961    public:
   2962       static bool enabled() { return CPUID::has_sse2(); }
   2963 
   2964       SIMD_SSE2(const u32bit B[4])
   2965          {
   2966          reg = _mm_loadu_si128(reinterpret_cast<const __m128i*>(B));
   2967          }
```

**Comment by randombit** [comment]
I'll fix this properly but short term workaround is to use `--disable-sse2` when generating the amalgamation.

**Comment by webmaster128** [comment]
Now we have this issue for the dynamic lib as well (see Kullo CI)

```
python configure.py  --prefix=../install-botan --with-build-dir=../build-botan --link-method=hardlink  --build-mode=release
make --jobs 2 -f ../build-botan/Makefile 
```

**Comment by webmaster128** [comment]
Thanks for fixing the issue for non-amalgamations. It still exists for amalgamation builds:

```
$ ./configure.py --disable-shared --via-amalgamation && make
   INFO: Platform: OS="Linux" machine="i686" proc="i686"
   INFO: Guessing target OS is linux (use --os to set)
   INFO: Guessing to use compiler gcc (use --cc to set)
   INFO: Guessing target processor is a x86_32/i686 (use --cpu to set)
   INFO: Target is gcc-linux-x86_32-i686
   INFO: Skipping, by request only - cvc
   INFO: Skipping, dependency failure - sessions_sqlite3
   INFO: Skipping, incompatible CPU - mp_x86_64 simd_altivec
   INFO: Skipping, incompatible OS - beos_stats cryptoapi_rng win32_stats
   INFO: Skipping, incompatible compiler - mp_x86_32_msvc
   INFO: Skipping, loaded only if needed by dependency - dyn_load mp_generic simd_scalar
   INFO: Skipping, requires external dependency - boost bzip2 lzma openssl sqlite3 zlib
   INFO: Using MP module mp_x86_32
   INFO: Using SIMD module simd_sse2
   INFO: Loading modules adler32 aead aes aes_ni aes_ssse3 aont asn1 auto_rng base base64 bcrypt benchmark bigint block blowfish camellia cascade cast cbc cbc_mac ccm cfb chacha chacha20poly1305 clmul cmac codec_filt comb4p compression crc24 crc32 cryptobox ctr curve25519 datastor des dev_random dh dl_algo dl_group dlies dsa eax ec_gfp ec_group ecb ecc_key ecdh ecdsa egd elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa1_bsi emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm gost_28147 gost_3410 gost_3411 has160 hash hash_id hex hkdf hmac hmac_drbg hmac_rng hres_timer http_util idea idea_sse2 if_algo kasumi kdf kdf1 kdf2 keccak keypair lion locking_allocator mac mars mce mceies md2 md4 md5 mdx_hash mgf1 misty1 mode_pad modes mp mp_x86_32 noekeon noekeon_simd nr numbertheory ocb ofb oid_lookup openpgp par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pk_pad poly1305 prf_tls prf_x942 proc_walk pubkey rc2 rc4 rc5 rc6 rdrand rfc3394 rfc6979 rmd128 rmd160 rng rsa rw safer salsa20 seed serpent serpent_simd sessions_sql sha1 sha1_sse2 sha2_32 sha2_64 simd simd_sse2 siphash siv skein srp6 stream system_rng tea threefish threefish_avx2 tiger tls tss twofish unix_procs utils whirlpool x509 x919_mac x931_rng xtea xtea_simd xts
   INFO: Assuming CPU is little endian
   INFO: Assuming unaligned memory access works
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation source to botan_all.cpp
   INFO: Writing amalgamation source to botan_all_aesni.cpp
   INFO: Writing amalgamation source to botan_all_ssse3.cpp
   INFO: Writing amalgamation source to botan_all_sse2.cpp
   INFO: Writing amalgamation source to botan_all_rdrand.cpp
   INFO: Writing amalgamation source to botan_all_avx2.cpp
   INFO: Botan 1.11.21 (unreleased undated) build setup is complete
g++ -pthread -fstack-protector  -std=c++11 -D_REENTRANT -c -O2 -Wall -Wextra -Wstrict-aliasing -Wstrict-overflow=5 -Wcast-align -Wmissing-declarations -Wpointer-arith -Wcast-qual -Wzero-as-null-pointer-constant -Ibuild/include botan_all.cpp -o build/obj/lib/botan_all.o
In file included from botan_all_internal.h:2720:0,
                 from botan_all.cpp:9:
/usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled"
 # error "SSE2 instruction set not enabled"
   ^
In file included from botan_all.cpp:9:0:
botan_all_internal.h:2864:25: error: expected ‘)’ before ‘in’
       SIMD_SSE2(__m128i in) { reg = in; }
                         ^
botan_all_internal.h:2866:7: error: ‘__m128i’ does not name a type
       __m128i reg;
       ^
botan_all_internal.h: In constructor ‘Botan::SIMD_SSE2::SIMD_SSE2(const u32bit*)’:
botan_all_internal.h:2729:10: error: ‘reg’ was not declared in this scope
          reg = _mm_loadu_si128(reinterpret_cast<const __m128i*>(B));
          ^
botan_all_internal.h:2729:55: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
          reg = _mm_loadu_si128(reinterpret_cast<const __m128i*>(B));
                                                       ^
botan_all_internal.h:2729:55: error: expected ‘>’ before ‘__m128i’
botan_all_internal.h:2729:55: error: expected ‘(’ before ‘__m128i’
botan_all_internal.h:2729:55: error: ‘__m128i’ was not declared in this scope
botan_all_internal.h:2729:63: error: expected primary-expression before ‘>’ token
          reg = _mm_loadu_si128(reinterpret_cast<const __m128i*>(B));
                                                               ^
botan_all_internal.h: In constructor ‘Botan::SIMD_SSE2::SIMD_SSE2(Botan::u32bit, Botan::u32bit, Botan::u32bit, Botan::u32bit)’:
botan_all_internal.h:2734:10: error: ‘reg’ was not declared in this scope
          reg = _mm_set_epi32(B0, B1, B2, B3);
          ^
botan_all_internal.h:2734:44: error: ‘_mm_set_epi32’ was not declared in this scope
          reg = _mm_set_epi32(B0, B1, B2, B3);
                                            ^
botan_all_internal.h: In constructor ‘Botan::SIMD_SSE2::SIMD_SSE2(Botan::u32bit)’:
botan_all_internal.h:2739:10: error: ‘reg’ was not declared in this scope
          reg = _mm_set1_epi32(B);
          ^
botan_all_internal.h:2739:32: error: ‘_mm_set1_epi32’ was not declared in this scope
          reg = _mm_set1_epi32(B);
                                ^
botan_all_internal.h: In static member function ‘static Botan::SIMD_SSE2 Botan::SIMD_SSE2::load_le(const void*)’:
botan_all_internal.h:2744:56: error: ISO C++ forbids declaration of ‘type name’ with no type [-fpermissive]
          return _mm_loadu_si128(reinterpret_cast<const __m128i*>(in));
                                                        ^
botan_all_internal.h:2744:56: error: expected ‘>’ before ‘__m128i’
botan_all_internal.h:2744:56: error: expected ‘(’ before ‘__m128i’
botan_all_internal.h:2744:56: error: ‘__m128i’ was not declared in this scope
botan_all_internal.h:2744:64: error: expected primary-expression before ‘>’ token
          return _mm_loadu_si128(reinterpret_cast<const __m128i*>(in));
                                                                ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::store_le(Botan::byte*) const’:
botan_all_internal.h:2754:44: error: expected type-specifier before ‘__m128i’
          _mm_storeu_si128(reinterpret_cast<__m128i*>(out), reg);
                                            ^
botan_all_internal.h:2754:44: error: expected ‘>’ before ‘__m128i’
botan_all_internal.h:2754:44: error: expected ‘(’ before ‘__m128i’
botan_all_internal.h:2754:44: error: ‘__m128i’ was not declared in this scope
botan_all_internal.h:2754:52: error: expected primary-expression before ‘>’ token
          _mm_storeu_si128(reinterpret_cast<__m128i*>(out), reg);
                                                    ^
botan_all_internal.h:2754:60: error: ‘reg’ was not declared in this scope
          _mm_storeu_si128(reinterpret_cast<__m128i*>(out), reg);
                                                            ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::rotate_left(std::size_t)’:
botan_all_internal.h:2764:10: error: ‘reg’ was not declared in this scope
          reg = _mm_or_si128(_mm_slli_epi32(reg, static_cast<int>(rot)),
          ^
botan_all_internal.h:2764:70: error: ‘_mm_slli_epi32’ was not declared in this scope
          reg = _mm_or_si128(_mm_slli_epi32(reg, static_cast<int>(rot)),
                                                                      ^
botan_all_internal.h:2765:73: error: ‘_mm_srli_epi32’ was not declared in this scope
                             _mm_srli_epi32(reg, static_cast<int>(32-rot)));
                                                                         ^
botan_all_internal.h:2765:74: error: ‘_mm_or_si128’ was not declared in this scope
                             _mm_srli_epi32(reg, static_cast<int>(32-rot)));
                                                                          ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::operator+=(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2775:10: error: ‘reg’ was not declared in this scope
          reg = _mm_add_epi32(reg, other.reg);
          ^
botan_all_internal.h:2775:41: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          reg = _mm_add_epi32(reg, other.reg);
                                         ^
botan_all_internal.h:2775:44: error: ‘_mm_add_epi32’ was not declared in this scope
          reg = _mm_add_epi32(reg, other.reg);
                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator+(const Botan::SIMD_SSE2&) const’:
botan_all_internal.h:2780:31: error: ‘reg’ was not declared in this scope
          return _mm_add_epi32(reg, other.reg);
                               ^
botan_all_internal.h:2780:42: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          return _mm_add_epi32(reg, other.reg);
                                          ^
botan_all_internal.h:2780:45: error: ‘_mm_add_epi32’ was not declared in this scope
          return _mm_add_epi32(reg, other.reg);
                                             ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::operator-=(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2785:10: error: ‘reg’ was not declared in this scope
          reg = _mm_sub_epi32(reg, other.reg);
          ^
botan_all_internal.h:2785:41: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          reg = _mm_sub_epi32(reg, other.reg);
                                         ^
botan_all_internal.h:2785:44: error: ‘_mm_sub_epi32’ was not declared in this scope
          reg = _mm_sub_epi32(reg, other.reg);
                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator-(const Botan::SIMD_SSE2&) const’:
botan_all_internal.h:2790:31: error: ‘reg’ was not declared in this scope
          return _mm_sub_epi32(reg, other.reg);
                               ^
botan_all_internal.h:2790:42: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          return _mm_sub_epi32(reg, other.reg);
                                          ^
botan_all_internal.h:2790:45: error: ‘_mm_sub_epi32’ was not declared in this scope
          return _mm_sub_epi32(reg, other.reg);
                                             ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::operator^=(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2795:10: error: ‘reg’ was not declared in this scope
          reg = _mm_xor_si128(reg, other.reg);
          ^
botan_all_internal.h:2795:41: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          reg = _mm_xor_si128(reg, other.reg);
                                         ^
botan_all_internal.h:2795:44: error: ‘_mm_xor_si128’ was not declared in this scope
          reg = _mm_xor_si128(reg, other.reg);
                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator^(const Botan::SIMD_SSE2&) const’:
botan_all_internal.h:2800:31: error: ‘reg’ was not declared in this scope
          return _mm_xor_si128(reg, other.reg);
                               ^
botan_all_internal.h:2800:42: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          return _mm_xor_si128(reg, other.reg);
                                          ^
botan_all_internal.h:2800:45: error: ‘_mm_xor_si128’ was not declared in this scope
          return _mm_xor_si128(reg, other.reg);
                                             ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::operator|=(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2805:10: error: ‘reg’ was not declared in this scope
          reg = _mm_or_si128(reg, other.reg);
          ^
botan_all_internal.h:2805:40: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          reg = _mm_or_si128(reg, other.reg);
                                        ^
botan_all_internal.h:2805:43: error: ‘_mm_or_si128’ was not declared in this scope
          reg = _mm_or_si128(reg, other.reg);
                                           ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator&(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2810:31: error: ‘reg’ was not declared in this scope
          return _mm_and_si128(reg, other.reg);
                               ^
botan_all_internal.h:2810:42: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          return _mm_and_si128(reg, other.reg);
                                          ^
botan_all_internal.h:2810:45: error: ‘_mm_and_si128’ was not declared in this scope
          return _mm_and_si128(reg, other.reg);
                                             ^
botan_all_internal.h: In member function ‘void Botan::SIMD_SSE2::operator&=(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2815:10: error: ‘reg’ was not declared in this scope
          reg = _mm_and_si128(reg, other.reg);
          ^
botan_all_internal.h:2815:41: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          reg = _mm_and_si128(reg, other.reg);
                                         ^
botan_all_internal.h:2815:44: error: ‘_mm_and_si128’ was not declared in this scope
          reg = _mm_and_si128(reg, other.reg);
                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator<<(std::size_t) const’:
botan_all_internal.h:2820:32: error: ‘reg’ was not declared in this scope
          return _mm_slli_epi32(reg, static_cast<int>(shift));
                                ^
botan_all_internal.h:2820:60: error: ‘_mm_slli_epi32’ was not declared in this scope
          return _mm_slli_epi32(reg, static_cast<int>(shift));
                                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator>>(std::size_t) const’:
botan_all_internal.h:2825:32: error: ‘reg’ was not declared in this scope
          return _mm_srli_epi32(reg, static_cast<int>(shift));
                                ^
botan_all_internal.h:2825:60: error: ‘_mm_srli_epi32’ was not declared in this scope
          return _mm_srli_epi32(reg, static_cast<int>(shift));
                                                            ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::operator~() const’:
botan_all_internal.h:2830:31: error: ‘reg’ was not declared in this scope
          return _mm_xor_si128(reg, _mm_set1_epi32(0xFFFFFFFF));
                               ^
botan_all_internal.h:2830:61: error: ‘_mm_set1_epi32’ was not declared in this scope
          return _mm_xor_si128(reg, _mm_set1_epi32(0xFFFFFFFF));
                                                             ^
botan_all_internal.h:2830:62: error: ‘_mm_xor_si128’ was not declared in this scope
          return _mm_xor_si128(reg, _mm_set1_epi32(0xFFFFFFFF));
                                                              ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::andc(const Botan::SIMD_SSE2&)’:
botan_all_internal.h:2836:34: error: ‘reg’ was not declared in this scope
          return _mm_andnot_si128(reg, other.reg);
                                  ^
botan_all_internal.h:2836:45: error: ‘const class Botan::SIMD_SSE2’ has no member named ‘reg’
          return _mm_andnot_si128(reg, other.reg);
                                             ^
botan_all_internal.h:2836:48: error: ‘_mm_andnot_si128’ was not declared in this scope
          return _mm_andnot_si128(reg, other.reg);
                                                ^
botan_all_internal.h: In member function ‘Botan::SIMD_SSE2 Botan::SIMD_SSE2::bswap() const’:
botan_all_internal.h:2841:10: error: ‘__m128i’ was not declared in this scope
          __m128i T = reg;
          ^
botan_all_internal.h:2841:18: error: expected ‘;’ before ‘T’
          __m128i T = reg;
                  ^
botan_all_internal.h:2843:10: error: ‘T’ was not declared in this scope
          T = _mm_shufflehi_epi16(T, _MM_SHUFFLE(2, 3, 0, 1));
          ^
botan_all_internal.h:2843:59: error: ‘_MM_SHUFFLE’ was not declared in this scope
          T = _mm_shufflehi_epi16(T, _MM_SHUFFLE(2, 3, 0, 1));
                                                           ^
botan_all_internal.h:2843:60: error: ‘_mm_shufflehi_epi16’ was not declared in this scope
          T = _mm_shufflehi_epi16(T, _MM_SHUFFLE(2, 3, 0, 1));
                                                            ^
botan_all_internal.h:2844:60: error: ‘_mm_shufflelo_epi16’ was not declared in this scope
          T = _mm_shufflelo_epi16(T, _MM_SHUFFLE(2, 3, 0, 1));
                                                            ^
botan_all_internal.h:2846:49: error: ‘_mm_srli_epi16’ was not declared in this scope
          return _mm_or_si128(_mm_srli_epi16(T, 8),
                                                 ^
botan_all_internal.h:2847:49: error: ‘_mm_slli_epi16’ was not declared in this scope
                              _mm_slli_epi16(T, 8));
                                                 ^
botan_all_internal.h:2847:50: error: ‘_mm_or_si128’ was not declared in this scope
                              _mm_slli_epi16(T, 8));
                                                  ^
botan_all_internal.h: In static member function ‘static void Botan::SIMD_SSE2::transpose(Botan::SIMD_SSE2&, Botan::SIMD_SSE2&, Botan::SIMD_SSE2&, Botan::SIMD_SSE2&)’:
botan_all_internal.h:2853:10: error: ‘__m128i’ was not declared in this scope
          __m128i T0 = _mm_unpacklo_epi32(B0.reg, B1.reg);
          ^
botan_all_internal.h:2853:18: error: expected ‘;’ before ‘T0’
          __m128i T0 = _mm_unpacklo_epi32(B0.reg, B1.reg);
                  ^
botan_all_internal.h:2854:18: error: expected ‘;’ before ‘T1’
          __m128i T1 = _mm_unpacklo_epi32(B2.reg, B3.reg);
                  ^
botan_all_internal.h:2855:18: error: expected ‘;’ before ‘T2’
          __m128i T2 = _mm_unpackhi_epi32(B0.reg, B1.reg);
                  ^
botan_all_internal.h:2856:18: error: expected ‘;’ before ‘T3’
          __m128i T3 = _mm_unpackhi_epi32(B2.reg, B3.reg);
                  ^
botan_all_internal.h:2857:13: error: ‘class Botan::SIMD_SSE2’ has no member named ‘reg’
          B0.reg = _mm_unpacklo_epi64(T0, T1);
             ^
botan_all_internal.h:2857:38: error: ‘T0’ was not declared in this scope
          B0.reg = _mm_unpacklo_epi64(T0, T1);
                                      ^
botan_all_internal.h:2857:42: error: ‘T1’ was not declared in this scope
          B0.reg = _mm_unpacklo_epi64(T0, T1);
                                          ^
botan_all_internal.h:2857:44: error: ‘_mm_unpacklo_epi64’ was not declared in this scope
          B0.reg = _mm_unpacklo_epi64(T0, T1);
                                            ^
botan_all_internal.h:2858:13: error: ‘class Botan::SIMD_SSE2’ has no member named ‘reg’
          B1.reg = _mm_unpackhi_epi64(T0, T1);
             ^
botan_all_internal.h:2858:44: error: ‘_mm_unpackhi_epi64’ was not declared in this scope
          B1.reg = _mm_unpackhi_epi64(T0, T1);
                                            ^
botan_all_internal.h:2859:13: error: ‘class Botan::SIMD_SSE2’ has no member named ‘reg’
          B2.reg = _mm_unpacklo_epi64(T2, T3);
             ^
botan_all_internal.h:2859:38: error: ‘T2’ was not declared in this scope
          B2.reg = _mm_unpacklo_epi64(T2, T3);
                                      ^
botan_all_internal.h:2859:42: error: ‘T3’ was not declared in this scope
          B2.reg = _mm_unpacklo_epi64(T2, T3);
                                          ^
botan_all_internal.h:2860:13: error: ‘class Botan::SIMD_SSE2’ has no member named ‘reg’
          B3.reg = _mm_unpackhi_epi64(T2, T3);
             ^
botan_all.cpp: In static member function ‘static std::pair<Botan::polyn_gf2m, Botan::polyn_gf2m> Botan::polyn_gf2m::eea_with_coefficients(const Botan::polyn_gf2m&, const Botan::polyn_gf2m&, int)’:
botan_all.cpp:25909:53: warning: assuming signed overflow does not occur when reducing constant in comparison [-Wstrict-overflow]
             cond1 =  r0.get_degree() <= break_deg - 1;
                                                     ^
make: *** [build/obj/lib/botan_all.o] Error 1

```

**Comment by webmaster128** [comment]
I think this is done via #549. Confirm

```
git checkout 1.11.30 && ./configure.py --disable-shared --via-amalgamation && make
// fail
```

```
git checkout cbe70db41212 && ./configure.py --disable-shared --via-amalgamation && make
// ok
```

on a Linux32 system.

**Comment by webmaster128** [comment]
After re-enabling the debugging-change in 5d50db6e964a, the error is back.

**Comment by randombit** [comment]
Works for me. SSE2 code gets split out to its own file that is compiled with -msse2
