### ISSUE TITLE
Various test failures

### ISSUE THREAD

**Issue by neusdan** [randombit/botan#369]
I'm encountering various test failures when not all modules are enabled.

For example: I have enabled `kdf` and `hkdf` but not `kdf1`.
The test runner will execute tests for all KDFs, so the tests for kdf1 are failing:

```
HKDF(SHA-1) ran 4 tests in 0.08 msec all ok
HKDF(SHA-256) ran 3 tests in 0.12 msec all ok
HKDF(SHA-512) ran 5 tests in 0.20 msec all ok
KDF1(SHA-1) ran 5 tests 5 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "KDF1(SHA-1)"'
Failure 2: test 2 failed with exception 'Could not find any algorithm named "KDF1(SHA-1)"'
Failure 3: test 3 failed with exception 'Could not find any algorithm named "KDF1(SHA-1)"'
Failure 4: test 4 failed with exception 'Could not find any algorithm named "KDF1(SHA-1)"'
Failure 5: test 5 failed with exception 'Could not find any algorithm named "KDF1(SHA-1)"
```

Here are the remaining results:
```
Failure 1: test 1 failed with exception 'Could not find any algorithm named "X9.42-PRF(1.2.840.113549.1.9.16.3.6)"'
X9.42-PRF(KeyWrap.RC2) ran 1 tests 1 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "X9.42-PRF(KeyWrap.RC2)"'
X9.42-PRF(KeyWrap.TripleDES) ran 1 tests 1 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "X9.42-PRF(KeyWrap.TripleDES)"'
PBKDF1(MD2) ran 4 tests 4 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "PBKDF1(MD2)"'
Failure 2: test 2 failed with exception 'Could not find any algorithm named "PBKDF1(MD2)"'
Failure 3: test 3 failed with exception 'Could not find any algorithm named "PBKDF1(MD2)"'
Failure 4: test 4 failed with exception 'Could not find any algorithm named "PBKDF1(MD2)"'
PBKDF1(SHA-1) ran 5 tests 5 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "PBKDF1(SHA-1)"'
Failure 2: test 2 failed with exception 'Could not find any algorithm named "PBKDF1(SHA-1)"'
Failure 3: test 3 failed with exception 'Could not find any algorithm named "PBKDF1(SHA-1)"'
Failure 4: test 4 failed with exception 'Could not find any algorithm named "PBKDF1(SHA-1)"'
Failure 5: test 5 failed with exception 'Could not find any algorithm named "PBKDF1(SHA-1)"'
PBKDF2(CMAC(Blowfish)) ran 1 tests 1 FAILED
Failure 1: test 1 failed with exception 'Could not find any algorithm named "PBKDF2(CMAC(Blowfish))"'

Failure 1: FFI botan_bcrypt_generate unexpectedly failed with error code -40
Failure 2: FFI bcrypt output size produced unexpected result 64 expected 61
Failure 3: FFI botan_bcrypt_is_valid unexpectedly failed with error code -40

Failure 1: test 3 failed with exception 'Creating 'RSA/EMSA2(SHA-1)' failed: Could not find any algorithm named "EMSA2(SHA-1)"'
Failure 2: test 4 failed with exception 'Creating 'RSA/EMSA2(SHA-1)' failed: Could not find any algorithm named "EMSA2(SHA-1)"'
Failure 3: test 5 failed with exception 'Creating 'RSA/EMSA2(SHA-224)' failed: Could not find any algorithm named "EMSA2(SHA-224)"'
Failure 4: test 6 failed with exception 'Creating 'RSA/EMSA2(SHA-224)' failed: Could not find any algorithm named "EMSA2(SHA-224)"'
Failure 5: test 7 failed with exception 'Creating 'RSA/EMSA2(SHA-224)' failed: Could not find any algorithm named "EMSA2(SHA-224)"'
Failure 6: test 8 failed with exception 'Creating 'RSA/EMSA2(SHA-224)' failed: Could not find any algorithm named "EMSA2(SHA-224)"'
Failure 7: test 9 failed with exception 'Creating 'RSA/EMSA2(SHA-256)' failed: Could not find any algorithm named "EMSA2(SHA-256)"'
Failure 8: test 10 failed with exception 'Creating 'RSA/EMSA2(SHA-256)' failed: Could not find any algorithm named "EMSA2(SHA-256)"'
Failure 9: test 11 failed with exception 'Creating 'RSA/EMSA2(SHA-256)' failed: Could not find any algorithm named "EMSA2(SHA-256)"'
Failure 10: test 12 failed with exception 'Creating 'RSA/EMSA2(SHA-256)' failed: Could not find any algorithm named "EMSA2(SHA-256)"'
Failure 11: test 13 failed with exception 'Creating 'RSA/EMSA2(SHA-384)' failed: Could not find any algorithm named "EMSA2(SHA-384)"'
Failure 12: test 14 failed with exception 'Creating 'RSA/EMSA2(SHA-384)' failed: Could not find any algorithm named "EMSA2(SHA-384)"'
Failure 13: test 15 failed with exception 'Creating 'RSA/EMSA2(SHA-384)' failed: Could not find any algorithm named "EMSA2(SHA-384)"'
Failure 14: test 16 failed with exception 'Creating 'RSA/EMSA2(SHA-384)' failed: Could not find any algorithm named "EMSA2(SHA-384)"'
Failure 15: test 17 failed with exception 'Creating 'RSA/EMSA2(SHA-512)' failed: Could not find any algorithm named "EMSA2(SHA-512)"'
Failure 16: test 18 failed with exception 'Creating 'RSA/EMSA2(SHA-512)' failed: Could not find any algorithm named "EMSA2(SHA-512)"'
Failure 17: test 19 failed with exception 'Creating 'RSA/EMSA2(SHA-512)' failed: Could not find any algorithm named "EMSA2(SHA-512)"'
Failure 18: test 20 failed with exception 'Creating 'RSA/EMSA2(SHA-512)' failed: Could not find any algorithm named "EMSA2(SHA-512)"'
Failure 19: test 21 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-128)' failed: Could not find any algorithm named "EMSA2(RIPEMD-128)"'
Failure 20: test 22 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-128)' failed: Could not find any algorithm named "EMSA2(RIPEMD-128)"'
Failure 21: test 23 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-128)' failed: Could not find any algorithm named "EMSA2(RIPEMD-128)"'
Failure 22: test 24 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-128)' failed: Could not find any algorithm named "EMSA2(RIPEMD-128)"'
Failure 23: test 25 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-160)' failed: Could not find any algorithm named "EMSA2(RIPEMD-160)"'
Failure 24: test 26 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-160)' failed: Could not find any algorithm named "EMSA2(RIPEMD-160)"'
Failure 25: test 27 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-160)' failed: Could not find any algorithm named "EMSA2(RIPEMD-160)"'
Failure 26: test 28 failed with exception 'Creating 'RSA/EMSA2(RIPEMD-160)' failed: Could not find any algorithm named "EMSA2(RIPEMD-160)"'
Failure 27: test 29 failed with exception 'Creating 'RSA/EMSA2(Whirlpool)' failed: Could not find any algorithm named "EMSA2(Whirlpool)"'
Failure 28: test 30 failed with exception 'Creating 'RSA/EMSA2(Whirlpool)' failed: Could not find any algorithm named "EMSA2(Whirlpool)"'
Failure 29: test 31 failed with exception 'Creating 'RSA/EMSA2(Whirlpool)' failed: Could not find any algorithm named "EMSA2(Whirlpool)"'
Failure 30: test 32 failed with exception 'Creating 'RSA/EMSA2(Whirlpool)' failed: Could not find any algorithm named "EMSA2(Whirlpool)"'
Failure 31: test 38 failed with exception 'Creating 'RSA/EMSA3(MD2)' failed: Could not find any algorithm named "EMSA3(MD2)"'
Failure 32: test 73 failed with exception 'Creating 'RSA/EMSA3(RIPEMD-160)' failed: Could not find any algorithm named "EMSA3(RIPEMD-160)"'
Failure 33: test 74 failed with exception 'Creating 'RSA/EMSA3(RIPEMD-160)' failed: Could not find any algorithm named "EMSA3(RIPEMD-160)"'
Failure 34: test 75 failed with exception 'Creating 'RSA/EMSA3(RIPEMD-160)' failed: Could not find any algorithm named "EMSA3(RIPEMD-160)"'
Failure 35: test 76 failed with exception 'Creating 'RSA/EMSA3(RIPEMD-160)' failed: Could not find any algorithm named "EMSA3(RIPEMD-160)"'
Failure 36: test 77 failed with exception 'Creating 'RSA/EMSA3(Tiger)' failed: Could not find any algorithm named "EMSA3(Tiger)"'
Failure 37: test 78 failed with exception 'Creating 'RSA/EMSA3(Tiger)' failed: Could not find any algorithm named "EMSA3(Tiger)"'
Failure 38: test 79 failed with exception 'Creating 'RSA/EMSA3(Tiger)' failed: Could not find any algorithm named "EMSA3(Tiger)"'
Failure 39: test 80 failed with exception 'Creating 'RSA/EMSA3(Tiger)' failed: Could not find any algorithm named "EMSA3(Tiger)"'

Failure 1: test 24 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 2: test 25 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 3: test 26 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 4: test 27 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'

```

**Comment by randombit** [comment]
Yeah these should be warnings rather than failures. I would not want them to silently skip after a bad experience of having a typo in the vector file causing tests that I thought were running to be skipped.

The ffi bcrypt test should accept the not-implemented error code as an alternative to producing a result. bcrypt is always exposed by ffi, even if we know bcrypt is disabled in the library build, because it prevents callers in Python etc from having to check for the existence of the symbol before calling it.

**Comment by randombit** [comment]
For KDF/PBKDF, the problem was caused by calling a function which threw instead of returning null on unknown. I think at least all the cases in the output you provided have been fixed, can you check latest master?

**Comment by neusdan** [comment]
Thanks the most is fixed. One more left:

```
 ran 4 tests 4 FAILED
Failure 1: test 24 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 2: test 25 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 3: test 26 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
Failure 4: test 27 failed with exception 'Creating 'RSA/EMSA4(RIPEMD-160)' failed: Could not find any algorithm named "EMSA4(RIPEMD-160)"'
```

**Comment by randombit** [comment]
I think 66fb50a should resolve that last one, can you confirm?

**Comment by neusdan** [comment]
It's not resolved. Still the same error.

The problem is in `PK_Signature_Verification_Test::run_one_test` during execution of the following statement:

`Botan::PK_Verifier verifier(*pubkey, padding);` 

it throws `Botan::Lookup_Error` for `padding = "EMSA4(RIPEMD-160)"`

**Comment by neusdan** [comment]
Everything fixed after 3467948. Thanks!

**Comment by neusdan** [comment]
Found some more test failures because of a missing `kdf1` module:

```
pubkey/mce.vec ran 6 tests 6 FAILED
Failure 1: test 1 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
Failure 2: test 2 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
Failure 3: test 3 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
Failure 4: test 4 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
Failure 5: test 5 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
Failure 6: test 6 failed with exception 'Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"'
mceliece ran 1 tests 1 FAILED
Failure 1: Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"
```

**Comment by neusdan** [comment]
One error remaining:
```
McEliece keygen ran 12 tests in 12.02 sec all ok
mceliece ran 1 tests 1 FAILED
Failure 1: Creating 'McEliece/KDF1(SHA-512)' failed: Could not find any algorithm named "KDF1(SHA-512)"
```

**Comment by neusdan** [comment]
I've looked into this error. The exception is thrown [here](https://github.com/randombit/botan/blob/e2a1b5450336889f3a1e01c4930e62d5a3def5b1/src/tests/test_mceliece.cpp#L220)

So for me it looks like that MCEIES depends on [KDF1](https://github.com/randombit/botan/blob/master/src/lib/pubkey/mceies/mceies.cpp#L39). 

So KDF1 should be a depended module of MCEIES module?!

**Comment by neusdan** [comment]
Thanks a lot

**Comment by webmaster128** [comment]
Done?

**Comment by neusdan** [comment]
yes, fixed
