### ISSUE TITLE
ld does not have option -soname on macosx

### ISSUE THREAD

**Issue by reitzig** [randombit/botan#861]
Building Botan as described [here](https://botan.randombit.net/manual/building.html#for-ios-using-xcode) fails with an error on Mac OSX; `ld` does not know option `-soname`.

Use `-install_name` instead.

Workaround: replace all occurences in the Makefile.

	cat Makefile | sed -e 's/-soname/-install_name/' > Makefile2;
  	mv Makefile2 Makefile;

**Comment by randombit** [comment]
Thanks for mentioning this problem, this is a result of a recent change. It should be fixed in the next few days.

**Comment by randombit** [comment]
This should be fixed now

**Comment by William-Froelich** [comment]
This issue is still present in Release 2.9.0.

Should this be re-opened or should it be considered a new issue?


```
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbotan-2.9.9.dylib] Error 1
```

```
commit a95c67a5a1fd8c9afd9cb69770cb1542f558f163 (HEAD, tag: 2.9.0, origin/release-2)
Author: Jack Lloyd <jack@randombit.net>
Date:   Fri Jan 4 11:14:58 2019 -0500

    Update for 2.9.0 release



```

**Comment by randombit** [comment]
@William-Froelich Please open a new issue including all output of `configure.py`
